server.port=8080
# server.servlet.context-path=/api/v1

spring.application.name=musicapp_backend
spring.datasource.url=jdbc:mysql://localhost:3306/musicapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=musicappuser
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# optional; auto-detected anyway
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# AWS S3 (demo defaults; change to your actual bucket/region)
aws.s3.bucket=musicapp-dev-bucket
aws.s3.region=eu-north-1

# 24 hours in ms
jwt.expiration=86400000

# to run this app you need to set these environment variables:
# JWT_SECRET
#
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY

